import SwiftUI

enum Language: String, CaseIterable, Identifiable {
    case turkish = "tr"
    case english = "en"
    
    var id: String { self.rawValue }
    
    var displayName: String {
        switch self {
        case .turkish: return "Türkçe"
        case .english: return "English"
        }
    }
}

class LanguageService: ObservableObject {
    @AppStorage("selectedLanguage") var selectedLanguage: Language = .english
    @AppStorage("isFirstLaunch_v3") var isFirstLaunch: Bool = true
    
    
    func s(_ key: String) -> String {
        return translations[selectedLanguage]?[key] ?? key
    }
    
    private let translations: [Language: [String: String]] = [
        .turkish: [
            "home": "Ana Sayfa",
            "downloading": "İndiriliyor",
            "queued": "Kuyrukta",
            "completed": "Tamamlandı",
            "history": "Geçmiş",
            "keyring": "Kimlik Bilgileri",
            "settings": "Ayarlar",
            "new_download": "Yeni İndirme Ekle",
            "url_placeholder": "YouTube ve binlerce siteden video indirin",
            "stat_downloading": "İndiriliyor",
            "stat_queued": "Kuyrukta",
            "stat_completed": "Tamamlandı",
            "stat_failed": "Hata",
            "empty_failed": "Başarısız indirme yok",
            "download_failed_error": "İndirme başarısız oldu: %@",
            "subtitle_download_failed": "Altyazı indirilemedi: %@",
            "too_many_requests": "Çok fazla istek (429). Lütfen Ayarlar > Gelişmiş kısmından bir tarayıcı (çerez) seçin.",
            "preferences": "Ayarlar",
            "general": "Genel",
            "download": "İndirme",
            "advanced": "Gelişmiş",
            "about": "Hakkında",
            "theme": "Tema",
            "system": "Sistem",
            "light": "Açık",
            "dark": "Koyu",
            "language": "Dil",
            "save_folder": "Varsayılan Kayıt Yeri",
            "select": "Seç...",
            "updates": "Güncellemeler",
            "check_updates": "Kontrol Et",
            "update_now": "Güncelle",
            "format_settings": "Format Ayarları",
            "file_type": "Varsayılan Dosya Tipi",
            "video_quality": "Varsayılan Video Kalitesi",
            "embed_options": "Gömme Seçenekleri",
            "embed_thumbnail": "Kapak resmini göm",
            "embed_metadata": "Metadata'yı göm",
            "concurrent_downloads": "Eşzamanlı İndirmeler",
            "max": "Maksimum",
            "sponsorblock_desc": "SponsorBlock, YouTube videolarındaki sponsor segmentlerini otomatik olarak atlar.",
            "ytdlp_update": "yt-dlp'yi Güncelle",
            "update_complete": "✅ Güncelleme tamamlandı!",
            "update_error": "❌ Hata:",
            "downloading_ytdlp": "İndiriliyor...",
            "version": "Versiyon",
            "special_thanks": "Özel Teşekkür",
            "credits": "Katkıda Bulunanlar",
            "license": "Lisans",
            "license_desc": "Bu yazılım özgür yazılımdır. Değiştirebilir ve dağıtabilirsiniz.",
            "supported_sites": "Desteklenen Siteler",
            "other": "Diğer",
            "empty_downloading": "Şu an indirilen video yok",
            "empty_queued": "Kuyrukta bekleyen video yok",
            "empty_completed": "Tamamlandı indirme yok",
            "video": "Video",
            "audio": "Ses",
            "default_video_resolution": "Varsayılan Video Çözünürlüğü",
            "sponsorblock": "SponsorBlock",
            "app_updates": "Uygulama Güncellemesi",
            "app_up_to_date": "Uygulama güncel",
            "downloading_update": "Güncelleme indiriliyor...",
            "installing_update": "Güncelleme kuruluyor ve yeniden başlatılıyor...",
            "update_failed": "Güncelleme başarısız oldu!",
            "restart_to_install": "Yeniden Başlat ve Kur",
            "update_available_title": "Yeni Güncelleme Mevcut!",
            "update_available_message": "Macabolic'in yeni sürümü (v%@) hazır. Şimdi indirmek ister misiniz?",
            "later": "Daha Sonra",
            "whats_new_title": "Macabolic v3.1.0 - Yenilikler 🚀",
            "whats_new_message": "✨ Yeni Özellikler (Beta):\n• Menü Barı Uygulaması: İndirmelerinizi doğrudan menü çubuğundan yönetin.\n• Chrome & Firefox Eklentisi: Tarayıcınızdan tek tıkla indirme başlatın.\n• Bildirim Desteği: İndirmeler bittiğinde anında haberdar olun.\n• Otomatik Başlatma: Mac'iniz açıldığında Macabolic hazır olsun.\n\n🔧 Diğer Önemli Değişiklikler:\n• UI İyileştirmeleri: Ana sayfa düzeni ve tam ekran deneyimi büyük ekranlar için optimize edildi.\n• Yerelleştirme Düzeltmeleri: Klasör seçim sayfalarındaki hardcoded \"Seç\" butonu düzeltildi.\n• Sponsorlar & Topluluk: Sponsor listesi güncellendi ve sabit \"GitHub'da Yıldızla\" butonu eklendi. Iman Montajabi ve Semmelstulle'ye teşekkürler.\n• Preset sorunları giderildi.\n• Sosyal medyada paylaşma özelliği eklendi.",
            "star_github": "GitHub'da Yıldızla",
            "special_thanks_sidebar": "Özel destekleri için",
            "for_support": "teşekkür ederiz.",
            "latest": "En son",
            "original_project": "Orijinal Proje",
            "view_license": "Lisansı Görüntüle",
            "app_desc": "YouTube ve binlerce siteden video indirmenizi sağlayan modern bir macOS uygulaması.",
            "extra_settings": "Ekstra Ayarlar",
            "video_url": "Video URL'si",
            "url_hint": "YouTube, Vimeo, Twitter ve daha fazlası...",
            "additional_arguments": "Ek Komutlar (Advanced)",
            "additional_arguments_hint": "Örn: --limit-rate 5M --restrict-filenames",
            "additional_arguments_help": "Tüm komutları görmek için [resmi dokümantasyona](https://github.com/yt-dlp/yt-dlp#usage-and-options) bakabilirsiniz.",
            "paste_from_clipboard": "Panodan Yapıştır",
            "fetch_info": "Bilgi Al",
            "quality": "Kalite",
            "custom_filename_hint": "Dosya adı (boş bırakılırsa video başlığı kullanılır)",
            "subtitles": "Altyazılar",
            "download_subtitles": "Altyazıları indir",
            "languages": "Diller:",
            "embed_video": "Videoya göm",
            "embedded_data": "Gömülü Veriler",
            "metadata_desc": "Metadata göm (başlık, sanatçı vb.)",
            "split_chapters": "Bölümlere ayır",
            "sponsorblock_hint": "SponsorBlock (reklamları atla)",
            "cancel": "İptal",
            "download_btn": "İndir",
            "clear_history": "Geçmişi Temizle",
            "history_empty": "İndirme geçmişi boş",
            "history_desc": "Tamamlanan indirmeler burada görünecek",
            "search_history": "Geçmişte ara...",
            "play": "Oynat",
            "redownload": "Yeniden İndir",
            "copy_url": "URL Kopyala",
            "add_new": "Yeni Ekle",
            "keyring_empty": "Kimlik bilgisi yok",
            "keyring_desc": "Parola korumalı içeriklere erişmek için kimlik bilgisi ekleyin",
            "add_credential": "Kimlik Bilgisi Ekle",
            "new_credential": "Yeni Kimlik Bilgisi",
            "edit_credential": "Kimlik Bilgisini Düzenle",
            "name_hint": "Ad (örn: YouTube Premium)",
            "name": "Ad",
            "username": "Kullanıcı Adı",
            "password": "Şifre",
            "save": "Kaydet",
            "fetching": "Bilgi Alınıyor",
            "processing": "İşleniyor",
            "failed": "Hata",
            "paused": "Duraklatıldı",
            "stop_all": "Tümünü Durdur",
            "finder": "Finder'da Göster",
            "retry": "Tekrarla / Devam Et",
            "stop": "Durdur",
            "log": "Log Göster",
            "remove": "Kaldır",
            "download_log": "İndirme Logu",
            "close": "Kapat",
            "no_log": "Henüz log yok...",
            "codec": "Codec",
            "auto_h264": "Otomatik (H.264)",
            "codec_warning": "Not: 1080p üzeri çözünürlükler için lütfen AV1 veya VP9 codec'ini seçin.",
            "support_btn": "Macabolic'i Destekleyin",
            "clear": "Temizle",
            "format": "Format",
            "browser_cookies": "Giriş Kaynağı (Cookies)",
            "none": "Yok",
            "browser_hint": "Lütfen daha önce YouTube hesabınızla giriş yaptığınız bir tarayıcı seçiniz. macOS ilk kullanımda anahtar zinciri erişimi için şifre isteyebilir; 'Her Zaman İzin Ver'i seçerek süreci kalıcı olarak onaylayabilirsiniz.",
            "fix_signin_error": "Ayarlarda Çöz",
            "safari_warning": "Not: Safari çerezleri için Sistem Ayarları > Gizlilik ve Güvenlik > Tam Disk Erişimi kısmından Macabolic'e izin vermeniz gerekir. Safari dışı bir tarayıcı (Chrome, Brave vb.) kullanmanız çok daha kolay olacaktır.",
            "open_system_settings": "Sistem Ayarlarını Aç",
            "video_codec": "Video Codec",
            "audio_codec": "Ses Codec",
            "codec_auto": "Otomatik (En İyi)",
            "codec_settings": "Codec Ayarları",
            "reset_to_defaults": "Varsayılanlara Sıfırla",
            "download_presets": "İndirme Presetleri",
            "preset_best_quality": "En İyi Kalite",
            "preset_max_compatibility": "Maksimum Uyumluluk",
            "preset_smallest_size": "En Küçük Boyut",
            "preset_audio_only": "Sadece Ses",
            "preset_best_quality_desc": "AV1 + Opus, En yüksek kalite",
            "preset_max_compatibility_desc": "H.264 + AAC, Tüm cihazlarda çalışır",
            "preset_smallest_size_desc": "AV1 720p, En küçük dosya boyutu",
            "preset_audio_only_desc": "Sadece ses indir (M4A)",
            "apply_preset": "Preseti Uygula",
            "preferred_video_codec": "Tercih Edilen Video Codec",
            "preferred_audio_codec": "Tercih Edilen Ses Codec",
            "codec_fallback_note": "Not: Seçilen codec mevcut değilse otomatik olarak en iyi alternatif seçilir.",
            "res_best": "En İyi",
            "res_worst": "En Düşük",
            "subtitle_format": "Altyazı Formatı",
            "file_exists_title": "Dosya Zaten Mevcut",
            "file_exists_message": "Bu isimde bir dosya zaten var. Ne yapmak istersiniz?",
            "overwrite": "Üzerine Yaz",
            "add_number": "Dosya adının sonuna numara ekle",
            "h264_resolution_warning": "H.264 codec 1080p üstü çözünürlükleri desteklemez. Lütfen VP9 veya AV1 codec'i seçin ya da farklı bir preset kullanın.",
            "subtitle_output": "Altyazı Çıktısı",
            "subtitle_external": "Ayrı Dosya",
            "subtitle_embedded": "Gömülü",
            "h264_preset_info": "H.264 codec seçildi. Maksimum kalite 1080p ile sınırlıdır.",
            "download_completed_title": "İndirme Tamamlandı",
            "download_completed_body": "%@ başarıyla indirildi.",
            "download_failed_title": "İndirme Hatası",
            "download_failed_body": "%@ indirilirken bir hata oluştu.",
            "launch_at_login": "Sistem açılışında otomatik başlat",
            "start_in_background": "Arka planda başlat",
            "start_in_background_desc": "Açılışta yalnızca menü çubuğu ikonu görünür, Dock'ta gözükmez",
            "quit": "Çıkış",
            "open_macabolic": "Macabolic'i Aç",
            "show_main_window": "Ana Pencereyi Göster",
            "preset": "Preset",
            "standard": "Standart",
            "custom": "Özel",
            "notifications": "Bildirimler",
            "show_menubar_icon": "Menü Çubuğu Simgesini Göster",
            "first_sponsor": "İlk Sponsor",
            "test_notification": "Test Bildirimi Gönder"
        ],
        .english: [
            "home": "Home",
            "downloading": "Downloading",
            "queued": "Queued",
            "completed": "Completed",
            "history": "History",
            "keyring": "Keyring",
            "settings": "Settings",
            "new_download": "Add New Download",
            "url_placeholder": "Download video from YouTube and thousands of sites",
            "stat_downloading": "Downloading",
            "stat_queued": "Queued",
            "stat_completed": "Completed",
            "stat_failed": "Failed",
            "empty_failed": "No failed downloads",
            "download_failed_error": "Download failed: %@",
            "subtitle_download_failed": "Subtitle download failed: %@",
            "too_many_requests": "Too many requests (429). Please select a browser in Settings > Advanced.",
            "preferences": "Preferences",
            "general": "General",
            "download": "Download",
            "advanced": "Advanced",
            "about": "About",
            "theme": "Theme",
            "system": "System",
            "light": "Light",
            "dark": "Dark",
            "language": "Language",
            "save_folder": "Default Save Folder",
            "select": "Select...",
            "updates": "Updates",
            "check_updates": "Check for Updates",
            "update_now": "Update Now",
            "format_settings": "Format Settings",
            "file_type": "Default File Type",
            "video_quality": "Default Video Quality",
            "embed_options": "Embedding Options",
            "embed_thumbnail": "Embed Thumbnail",
            "embed_metadata": "Embed Metadata",
            "concurrent_downloads": "Concurrent Downloads",
            "max": "Maximum",
            "sponsorblock_desc": "SponsorBlock automatically skips sponsor segments in YouTube videos.",
            "ytdlp_update": "Update yt-dlp",
            "update_complete": "✅ Update complete!",
            "update_error": "❌ Error:",
            "downloading_ytdlp": "Downloading...",
            "version": "Version",
            "special_thanks": "Special Thanks",
            "credits": "Credits",
            "license": "License",
            "license_desc": "This software is free software. You can redistribute and modify it.",
            "supported_sites": "Supported Sites",
            "other": "Other",
            "empty_downloading": "No videos are currently being downloaded",
            "empty_queued": "No videos waiting in queue",
            "empty_completed": "No completed downloads",
            "video": "Video",
            "audio": "Audio",
            "default_video_resolution": "Default Video Resolution",
            "sponsorblock": "SponsorBlock",
            "app_updates": "App Updates",
            "app_up_to_date": "App is up to date",
            "downloading_update": "Downloading update...",
            "installing_update": "Installing update & restarting...",
            "update_failed": "Update failed!",
            "restart_to_install": "Restart and Install",
            "update_available_title": "New Update Available!",
            "update_available_message": "A new version of Macabolic (v%@) is ready. Would you like to download it now?",
            "later": "Later",
            "latest": "Latest",
            "original_project": "Original Project",
            "view_license": "View License",
            "cancel": "Cancel",
            "download_btn": "Download",
            "clear_history": "Clear History",
            "history_empty": "Download history is empty",
            "history_desc": "Completed downloads will appear here",
            "search_history": "Search in history...",
            "play": "Play",
            "redownload": "Re-download",
            "copy_url": "Copy URL",
            "add_new": "Add New",
            "keyring_empty": "No credentials",
            "keyring_desc": "Add credentials to access password-protected content",
            "add_credential": "Add Credential",
            "new_credential": "New Credential",
            "edit_credential": "Edit Credential",
            "name_hint": "Name (e.g. YouTube Premium)",
            "name": "Name",
            "username": "Username",
            "password": "Password",
            "save": "Save",
            "fetching": "Fetching Info...",
            "processing": "Processing...",
            "failed": "Failed",
            "paused": "Paused",
            "stop_all": "Stop All",
            "finder": "Show in Finder",
            "retry": "Retry / Resume",
            "stop": "Stop",
            "log": "Show Log",
            "remove": "Remove",
            "download_log": "Download Log",
            "close": "Close",
            "no_log": "No log yet...",
            "codec": "Codec",
            "auto_h264": "Auto (H.264)",
            "codec_warning": "Note: For resolutions higher than 1080p, please select AV1 or VP9 codec.",
            "clear": "Clear",
            "support_btn": "Support Macabolic",
            "format": "Format",
            "browser_cookies": "Login Source (Cookies)",
            "none": "None",
            "browser_hint": "Please select a browser where you have previously logged in with your YouTube account. macOS may ask for keychain access on first use; select 'Always Allow' to permanently authorize this.",
            "fix_signin_error": "Fix in Settings",
            "safari_warning": "Note: For Safari cookies, you must grant 'Full Disk Access' to Macabolic in System Settings > Privacy & Security. Using a browser other than Safari (Chrome, Brave, etc.) will be much easier.",
            "open_system_settings": "Open System Settings",
            "whats_new_title": "Macabolic v3.1.0 - What's New? 🚀",
            "whats_new_message": "✨ New Features (Beta):\n• Menu Bar App: Manage your downloads directly from the menu bar.\n• Chrome & Firefox Extension: Start downloads with one click from your browser.\n• Notification Support: Get notified instantly when downloads are finished.\n• Auto-launch: Macabolic is ready when your Mac starts.\n\n🔧 Other Important Changes:\n• UI Improvements: Optimized home view layout and full-screen experience for large displays.\n• Localization Fixes: Fixed hardcoded \"Select\" button in folder selection sheets.\n• Sponsors & Community: Updated sponsor list and added a static \"Star on GitHub\" button. Thanks for the Iman Montajabi and Semmelstulle.\n• Preset issues resolved.\n• Share on social media feature added.",
            "star_github": "Star on GitHub",
            "special_thanks_sidebar": "Special thanks to",
            "for_support": "for their support.",
            "video_codec": "Video Codec",
            "additional_arguments": "Additional Arguments (Command Line)",
            "additional_arguments_hint": "e.g. --limit-rate 5M --restrict-filenames",
            "additional_arguments_help": "Check the [official documentation](https://github.com/yt-dlp/yt-dlp#usage-and-options) for all available commands.",
            "audio_codec": "Audio Codec",
            "codec_auto": "Auto (Best Available)",
            "codec_settings": "Codec Settings",
            "reset_to_defaults": "Reset to Defaults",
            "download_presets": "Download Presets",
            "preset_best_quality": "Best Quality",
            "preset_max_compatibility": "Max Compatibility",
            "preset_smallest_size": "Smallest Size",
            "preset_audio_only": "Audio Only",
            "preset_best_quality_desc": "AV1 + Opus, Highest quality",
            "preset_max_compatibility_desc": "H.264 + AAC, Works on all devices",
            "preset_smallest_size_desc": "AV1 720p, Smallest file size",
            "preset_audio_only_desc": "Download audio only (M4A)",
            "apply_preset": "Apply Preset",
            "preferred_video_codec": "Preferred Video Codec",
            "preferred_audio_codec": "Preferred Audio Codec",
            "codec_fallback_note": "Note: If selected codec is unavailable, the best alternative will be used.",
            "res_best": "Best",
            "res_worst": "Worst",
            "subtitle_format": "Subtitle Format",
            "file_exists_title": "File Already Exists",
            "file_exists_message": "A file with this name already exists. What would you like to do?",
            "overwrite": "Overwrite",
            "add_number": "Add number to filename",
            "h264_resolution_warning": "H.264 codec doesn't support resolutions above 1080p. Please select VP9 or AV1 codec, or use a different preset.",
            "subtitle_output": "Subtitle Output",
            "subtitle_external": "Separate File",
            "subtitle_embedded": "Embedded",
            "h264_preset_info": "H.264 codec selected. Maximum quality is limited to 1080p.",
            "download_completed_title": "Download Completed",
            "download_completed_body": "%@ has been downloaded successfully.",
            "download_failed_title": "Download Failed",
            "download_failed_body": "An error occurred while downloading %@.",
            "launch_at_login": "Launch at login",
            "start_in_background": "Start in background",
            "start_in_background_desc": "Only show the menu bar icon at launch, hide from Dock",
            "quit": "Quit",
            "open_macabolic": "Open Macabolic",
            "show_main_window": "Show Main Window",
            "preset": "Preset",
            "standard": "Standard",
            "custom": "Custom",
            "notifications": "Notifications",
            "show_menubar_icon": "Show Menu Bar Icon",
            "first_sponsor": "First Sponsor",
            "test_notification": "Send Test Notification"
        ]
    ]
}
